
# total duration (s) of the recording after KWS is detected.
rec_duration: 4
rec_samplerate: 44100
rec_channels: 1

microphone_name: "MacBook Pro Microphone"

content:
    content_file: "./content/marvin_content_robot.json"

KWS:
    samplerate: 16000
    step_size: 0.5
    vad_window_size: 0.5
    mbn_window_size: 1.5
    channels: 1
    vad_threshold: 0.9 # the higher the less sensitive the vad is

models:
    asr_model: "stt_en_conformer_ctc_small"
    mbn_model: "commandrecognition_en_matchboxnet3x1x64_v2"
    vad_model: "vad_multilingual_marblenet"
